spring:
  application:
    name: gulimall-member
  cloud:
    sentinel:
      transport:
        port: 8723
        dashboard: 192.168.56.10:8090
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://192.168.56.10:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      min-idle: 5
      max-active: 100
  thymeleaf:
    cache: false
  redis:
    database: 0
    port: 6379
    host: 192.168.56.10
    password: root
  session:
    store-type: redis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 0
management:
  endpoints:
    web:
      exposure:
        include: '*'