spring:
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://192.168.56.10:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 60
      max-active: 2000
      min-idle: 50
      max-wait: 60000
      validation-query: select 1
      validation-query-timeout: 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30001
      async-close-connection-enable: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
  redis:
    database: 0
    port: 6379
    host: 192.168.56.10
    password: root
  cache:
    type: redis  #使用redis作为springcache
    redis:
      time-to-live:  -1  #单位毫秒  没有过期时间
  application:
    name: gulimall-product
  thymeleaf:
    cache: true   #开发阶段关闭页面缓存功能
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
feign:
  hystrix:
    enabled: true #开启熔断器
server:
  port: 0