spring:
  datasource:
    druid:
      enable: true
      username: root
      password: root
      url: jdbc:mysql://192.168.56.10:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 60
      max-active: 2000
      min-idle: 50
      max-wait: 60000
      validation-query: select 1
      validation-query-timeout: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30001
      async-close-connection-enable: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
     database: 0
     port: 6379
     host: 192.168.56.10
     password: root
  cloud:
    alicloud:
      access-key: LTAI4Fz5L3Cv3oddewnSaGDy
      secret-key: g9nZchfL4c6UYEi8tp7zAdM5rsXXJa
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
    alibaba:
      seata:
         tx-service-group: my_test_tx_group
    sentinel:
      transport:
        port: 8726
        dashboard: 192.168.56.10:8090
  cachecache:
    type: redis  #使用redis作为springcache
    redis:
      time-to-live:  -1  #单位毫秒  没有过期时间
  application:
    name: gulimall-product
  thymeleaf:
    cache: true   #开发阶段关闭页面缓存功能
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
feign:
  hystrix:
    enabled: true #开启熔断器
server:
  port: 14000
  undertow:
    io-threads: 4 # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    worker-threads: 120  # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    buffer-size: 2048  # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理 , 每块buffer的空间大小,越小的空间被利用越充分
    direct-buffers: true  # 是否分配的直接内存
management:
  endpoints:
    web:
      exposure:
        include: '*'
##配置订单数据库
gulimall:
  order:
    url: jdbc:mysql://192.168.56.10:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

