spring:
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://172.31.197.22:33306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      min-idle: 5
      max-active: 100
  cloud:
    nacos:
      discovery:
        server-addr: 172.31.197.22:18848
        namespace: 4cbfefb7-7281-4479-8047-6aff8ab48ac2
  application:
    name: gulimall-coupon

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 7000