spring:
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://192.168.56.10:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      min-idle: 5
      max-active: 100
  application:
    name: gulimall-coupon
  cloud:
    sentinel:
      transport:
        port: 8722
        dashboard: 192.168.56.10:8090
  task:
    execution:
      pool:
        max-size: 200
        core-size: 20
      thread-name-prefix: 异步线程
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss   #针对LocalDateTime类型的时间api不起作用,LocalDateTime需要用@JsonFormat
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 7000
  undertow:
    io-threads: 4 # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    worker-threads: 120  # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    buffer-size: 2048  # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理 , 每块buffer的空间大小,越小的空间被利用越充分
    direct-buffers: true  # 是否分配的直接内存
management:
  endpoints:
    web:
      exposure:
        include: '*'