spring:
  application:
    name: gulimall-search
  elasticsearch:
    hostname: 192.168.56.10
    port: 9200
    scheme: http
  redis:
    database: 0
    port: 6379
    host: 192.168.56.10
    password: root
  session:
    store-type: redis
server:
  port: 12000