server:
  port: 9001
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 10000
    jedis:
      pool:
        max-active: 6000
        max-wait: 1000
        max-idle: 400
        min-idle: 0
  cache:
    type: redis
    redis:
     time-to-live:  -1  #单位毫秒  没有过期时间