spring:
  application:
    name: gulimall-auther-server
  redis:
    database: 0
    port: 6379
    host: 192.168.56.10
    password: root
  session:
    store-type: redis
feign:
  hystrix:
    enabled: true #开启熔断器
server:
  port: 20000
  servlet:
    session:
      timeout: 30m



