spring:
  application:
    name: gulimall-cart
  cloud:
    sentinel:
      transport:
        port: 8721
        dashboard: 192.168.56.10:8090
  redis:
    database: 0
    port: 6379
    host: 192.168.56.10
    password: root
  session:
    store-type: redis
feign:
  hystrix:
    enabled: true #开启熔断器
server:
  port: 0
  servlet:
    session:
      timeout: 30m
management:
  endpoints:
    web:
      exposure:
        include: '*'



