spring:
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://172.31.197.22:33306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      min-idle: 5
      max-active: 100
  cloud:
    nacos:
      discovery:
        server-addr: 172.31.197.22:18848
  application:
    name: gulimall-ware

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000